# Generated by Django 2.1.7 on 2020-09-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='offList',
            fields=[
                ('lessonid', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='offList6',
            fields=[
                ('lessonid', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id', models.CharField(max_length=20, unique=True)),
                ('keymode', models.IntegerField(null=True)),
                ('ssmode', models.IntegerField(null=True)),
                ('transc', models.IntegerField(null=True)),
                ('lesson', models.IntegerField(null=True)),
                ('grades', models.IntegerField(null=True)),
                ('selected', models.IntegerField(null=True)),
                ('friend', models.IntegerField(null=True)),
                ('dateCreated', models.DateTimeField()),
                ('error', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stuxh',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=12)),
                ('institute', models.CharField(max_length=20, null=True)),
                ('major', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('index', 'id')},
        ),
    ]
